# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVPCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AVPCDemo
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

  target 'AVPCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
